"use client";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { DemoReport } from "@/components/demo-report";
import { PRIZE_BY_ID, classLabel, type EntryView, type EventInfo, type PrizeId } from "@/lib/game";
type Report={events:EventInfo[];activeEvent:string;crmConnected:boolean;totals:{registered:number;completed:number;draw_entries:number};funnel:{name:string;events:number;sessions:number}[];prizes:{prize_id:PrizeId;count:number;redeemed:number}[];classes:{class_level:string;count:number}[];outbox:{status:string;count:number}[];inventory:{event_id:string;prize_id:string;stock_limit:number|null;awarded:number}[]};
const stages=[['landing_view','ল্যান্ডিং'],['registration_view','ফর্ম দেখা'],['registration_started','ফর্ম শুরু'],['registration_completed','নিবন্ধন'],['wheel_view','চাকা দেখা'],['spin_completed','পুরস্কার পাওয়া'],['result_view','ফলাফল দেখা'],['collection_view','সংগ্রহের তথ্য'],['draw_view','EduTab দেখা'],['next_steps_view','অ্যাপ ও শেয়ার দেখা'],['share_opened','শেয়ার খোলা'],['share_completed','শেয়ার সম্পন্ন'],['whatsapp_click','WhatsApp ক্লিক'],['community_click','কমিউনিটি ক্লিক'],['app_click','অ্যাপ ক্লিক']];
export default function Ops(){
  const [report,setReport]=useState<Report|null>(null),[key,setKey]=useState(""),[auth,setAuth]=useState(false),[event,setEvent]=useState("");
  const [tab,setTab]=useState("analytics"),[error,setError]=useState(""),[busy,setBusy]=useState(false),[code,setCode]=useState(""),[entry,setEntry]=useState<EntryView|null>(null);
  const load=useCallback(async()=>{const res=await fetch(`/api/ops?event=${event}`,{cache:"no-store"});if(res.status===401){setAuth(false);return;}if(!res.ok)throw new Error("তথ্য লোড হয়নি। আবার চেষ্টা করুন।");setReport(await res.json());setAuth(true);},[event]);
  useEffect(()=>{let cancelled=false;fetch(`/api/ops?event=${event}`,{cache:"no-store"}).then(async res=>{
    if(cancelled)return;if(res.status===401){setAuth(false);return;}if(!res.ok)throw new Error("তথ্য লোড হয়নি। আবার চেষ্টা করুন।");
    const data=await res.json();if(!cancelled){setReport(data);setAuth(true);}
  }).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;};},[event]);
  async function login(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const res=await fetch("/api/ops/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({key})});if(!res.ok)throw new Error("সঠিক অপারেশনস কী দিন।");setKey("");await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function action(data:unknown){setBusy(true);setError("");try{const res=await fetch("/api/ops",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const json=await res.json();if(!res.ok)throw new Error(({redeemed:"আগেই সংগ্রহ করা হয়েছে।",expired:"অফারের মেয়াদ শেষ।",not_found:"এই কোড পাওয়া যায়নি।"} as Record<string,string>)[json.error]||"পরিবর্তন হয়নি। আবার চেষ্টা করুন।");if(json.entry)setEntry(json.entry);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  if(!auth)return <main className="ops-shell"><div className="ops-login"><h1>শিখো স্পিন অপারেশনস</h1><p>শুধু অনুমোদিত টিমের জন্য।</p><form onSubmit={login}><label htmlFor="ops-key">অপারেশনস কী</label><input id="ops-key" type="password" value={key} onChange={e=>setKey(e.target.value)} autoComplete="current-password"/><button className="button primary" disabled={busy}>প্রবেশ করুন</button></form>{error&&<p role="alert">{error}</p>}</div></main>;
  return <main className="ops-shell"><h1>শিখো স্পিন অপারেশনস</h1><div className="ops-tabs"><select aria-label="ইভেন্ট" value={event} onChange={e=>setEvent(e.target.value)}><option value="">সব ইভেন্ট</option>{report?.events.map(e=><option key={e.id} value={e.id}>{e.city}</option>)}</select><button onClick={()=>void load().catch(e=>setError(e.message))}>রিফ্রেশ</button><button onClick={async()=>{await fetch("/api/ops/login",{method:"DELETE",headers:{"Content-Type":"application/json"},body:"{}"});setAuth(false);setReport(null);}}>লগ আউট</button></div>
    <div className="ops-tabs" role="tablist" aria-label="অপারেশনস বিভাগ">{[["analytics","অ্যানালিটিক্স"],["redeem","পুরস্কার সংগ্রহ"],["stock","স্টক"],["events","ইভেন্ট"],["demo","ডেমো মতামত"]].map(([id,title])=><button key={id} role="tab" aria-selected={tab===id} onClick={()=>{setTab(id);setError("");}}>{title}</button>)}</div>
    {error&&<p className="error-notice" role="alert">{error}</p>}
    {tab==="demo"&&<DemoReport/>}
    {report&&tab==="analytics"&&<><div className="ops-summary"><div>নিবন্ধন<strong>{report.totals.registered}</strong></div><div>স্পিন সম্পন্ন<strong>{report.totals.completed}</strong></div><div>জাতীয় ড্র এন্ট্রি<strong>{report.totals.draw_entries}</strong></div></div>
      <h2>যাত্রার প্রতিটি ধাপ</h2><p className="ops-help">ব্রাউজারভিত্তিক স্বতন্ত্র সেশন। পরের ধাপে না যাওয়া সেশন থেকে ড্রপ-অফ বোঝা যাবে। শেয়ার ক্লিক মানেই পোস্ট বা অ্যাপ ইনস্টল নয়।</p>
      <div className="ops-table-wrap"><table><thead><tr><th>ধাপ</th><th>স্বতন্ত্র সেশন</th><th>মোট ইভেন্ট</th></tr></thead><tbody>{stages.map(([id,title])=>{const row=report.funnel.find(f=>f.name===id);return <tr key={id}><td>{title}</td><td>{row?.sessions||0}</td><td>{row?.events||0}</td></tr>;})}</tbody></table></div>
      <h2>পুরস্কার</h2><div className="ops-table-wrap"><table><thead><tr><th>পুরস্কার</th><th>জিতেছে</th><th>সংগ্রহ করেছে</th></tr></thead><tbody>{report.prizes.map(p=><tr key={p.prize_id}><td>{PRIZE_BY_ID.get(p.prize_id)?.title}</td><td>{p.count}</td><td>{p.redeemed}</td></tr>)}</tbody></table></div>
      <h2>ক্লাস</h2><div className="ops-table-wrap"><table><thead><tr><th>ক্লাস</th><th>নিবন্ধন</th></tr></thead><tbody>{report.classes.map(c=><tr key={c.class_level}><td>{classLabel(c.class_level)}</td><td>{c.count}</td></tr>)}</tbody></table></div>
      <h2>CRM ডেলিভারি</h2><p>{report.crmConnected?"CRM সংযুক্ত। নিবন্ধন ও ফলাফল স্বয়ংক্রিয়ভাবে পাঠানো হচ্ছে।":"CRM টোকেন কনফিগার করা হয়নি।"}</p>{report.outbox.map(o=><p key={o.status}>{o.status}: {o.count}</p>)}<button className="button secondary" style={{maxWidth:320,marginTop:16}} disabled={busy||!report.crmConnected} onClick={()=>void action({action:"crm_retry"})}>অপেক্ষমাণ ডেলিভারি আবার পাঠান</button>
    </>}
    {tab==="redeem"&&<><h2>টিকিট যাচাই করুন</h2><form onSubmit={e=>{e.preventDefault();setEntry(null);void action({action:"lookup",code:code.trim().toUpperCase()});}}><input aria-label="টিকিট কোড" placeholder="ARIF-78-K4M2" value={code} onChange={e=>setCode(e.target.value)} maxLength={80}/><button className="button primary" disabled={busy}>কোড দেখুন</button></form>
      {entry&&<div><h2>{entry.name}</h2><p>{entry.event.city} · {classLabel(entry.classLevel)} · {PRIZE_BY_ID.get(entry.prizeId!)?.title}</p><p>{entry.code}</p>{entry.redeemedAt?<p>সংগ্রহ করা হয়েছে।</p>:<button className="button primary" style={{maxWidth:320,marginTop:20}} disabled={busy} onClick={()=>void action({action:"redeem",code:entry.code})}>পুরস্কার দিয়ে সংগ্রহ নিশ্চিত করুন</button>}</div>}
    </>}
    {report&&tab==="stock"&&<><h2>প্রতি ইভেন্টের মোট স্টক সীমা</h2><p className="ops-help">খালি মানে সীমা নেই। ০ মানে এই পুরস্কার বন্ধ। সীমা শেষ হলে ওই সম্ভাবনায় ২০% ছাড় দেওয়া হবে।</p>{report.events.filter(e=>!event||e.id===event).map(e=><section key={e.id}><h2>{e.city}</h2>{["bag","book"].map(prize=>{const row=report.inventory.find(r=>r.event_id===e.id&&r.prize_id===prize);return <form key={prize} onSubmit={ev=>{ev.preventDefault();const raw=new FormData(ev.currentTarget).get("limit") as string;void action({action:"inventory",event:e.id,prize,limit:raw===""?null:Number(raw)});}}><label>{prize==="bag"?"ব্যাগ":"বই"} · দেওয়া হয়েছে {row?.awarded||0}<input name="limit" aria-label={`${e.city} ${prize} সীমা`} type="number" min="0" max="100000" placeholder="সীমা নেই" defaultValue={row?.stock_limit??""}/></label><button className="button secondary" disabled={busy}>সেভ</button></form>;})}</section>)}</>}
    {report&&tab==="events"&&<><h2>ইভেন্ট বদলান, একই QR রাখুন</h2><p className="ops-help">সক্রিয় ইভেন্ট মূল লিংকে দেখা যায়। প্রতিটি ইভেন্টের নিজস্ব লিংকও থাকে। পুরোনো টিকিটে আগের ইভেন্টই থাকবে।</p>
      <div className="ops-table-wrap"><table><thead><tr><th>শহর</th><th>তারিখ</th><th>লিংক</th><th>CRM</th><th>মূল পেজ</th></tr></thead><tbody>{report.events.map(e=><tr key={e.id}><td>{e.city}</td><td>{e.date}</td><td><a href={`/?event=${e.id}`} target="_blank" rel="noopener noreferrer">{e.id}</a></td><td>{e.crmReadyAt?"প্রস্তুত":<button className="text-button" disabled={busy||!report.crmConnected} onClick={()=>void action({action:"crm_provision",event:e.id})}>প্রস্তুত করুন</button>}</td><td>{report.activeEvent===e.id?"সক্রিয়":<button className="text-button" disabled={busy} onClick={()=>void action({action:"event",...e,active:true})}>সক্রিয় করুন</button>}</td></tr>)}</tbody></table></div>
      <h2>নতুন ইভেন্ট বা তথ্য সংশোধন</h2><form onSubmit={ev=>{ev.preventDefault();const f=new FormData(ev.currentTarget);void action({action:"event",id:f.get("id"),city:f.get("city"),name:f.get("name"),date:f.get("date"),active:f.get("active")==="on"});}}>
        <label>লিংক আইডি<input name="id" placeholder="dhaka" pattern="[a-z0-9-]{1,48}" required/></label><label>শহর<input name="city" placeholder="ঢাকা" required maxLength={60}/></label><label>ইভেন্টের নাম<input name="name" defaultValue="প্রথম আলো × শিখো সংবর্ধনা ২০২৬" required maxLength={120}/></label><label>তারিখ<input name="date" type="date" required/></label><label><input name="active" type="checkbox"/> মূল পেজে এখনই দেখান</label><button className="button primary" disabled={busy}>ইভেন্ট সেভ করুন</button>
      </form></>}
  </main>;
}
